version: "3.6"

services:
  tembazar_db:
    image: postgres:15.3
    shm_size: 256m
    container_name: tembazar_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - tembazar-network
    restart: always

  tembazar_backend:
    image: tembazar_backend:latest
    container_name: tembazar_backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - tembazar-network
    environment:
      - TZ=Europe/Moscow
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    volumes:
      - ${BACKEND}:/app
    depends_on:
      - tembazar_db
    command: uvicorn main:app --host 0.0.0.0 --root-path /api --port 8000
    restart: always

networks:
  tembazar-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_ADDRESS}
